# Copyright (c) mcp-checkup contributors.
# SPDX-License-Identifier: Apache-2.0

"""Turn schema compression into shippable fixes.

Builds a before/after report for a server's tools and emits the artifacts a
user can actually act on: sidecar schema files a server author can adopt
verbatim, a ready-to-paste GitHub issue body, and a rich terminal table.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console
from rich.table import Table

from mcp_checkup.compress import CompressPolicy, compress_schema, savings
from mcp_checkup.models import ServerInventory

MCP_CHECKUP_URL = "https://github.com/mohitgurnani1/mcp-checkup"
MCP_SPEC_ISSUE_URL = "https://github.com/modelcontextprotocol/modelcontextprotocol/issues/2808"

HONESTY_LINE = (
    "Your client still fetches the original schemas from the server; permanent fixes "
    "belong server-side (share the sidecars or the generated issue text), or use the "
    "trim proxy (v0.7)."
)

MEASUREMENT_NOTE = (
    "Token counts are estimates: each tool definition is serialized to the Anthropic "
    "Messages API wire format and tokenized with tiktoken's o200k_base encoding."
)


@dataclass
class FixRow:
    """Before/after token counts for one tool (Anthropic wire estimate)."""

    name: str
    before: int
    after: int

    @property
    def saved(self) -> int:
        return self.before - self.after


@dataclass
class FixReport:
    """Per-tool compression rows plus totals for one server."""

    server: str
    rows: list[FixRow] = field(default_factory=list)
    total_before: int = 0
    total_after: int = 0

    @property
    def total_saved(self) -> int:
        return self.total_before - self.total_after

    @property
    def pct_saved(self) -> float:
        """Percentage of tokens saved overall; 0.0 when there is nothing to count."""
        if self.total_before <= 0:
            return 0.0
        return 100.0 * self.total_saved / self.total_before


def build_report(inventory: ServerInventory, policy: CompressPolicy) -> FixReport:
    """Measure every tool in *inventory* under *policy* and total the results."""
    rows = []
    for tool in inventory.tools:
        before, after = savings(tool, policy)
        rows.append(FixRow(name=tool.name, before=before, after=after))
    return FixReport(
        server=inventory.spec.name,
        rows=rows,
        total_before=sum(r.before for r in rows),
        total_after=sum(r.after for r in rows),
    )


def emit_sidecars(inventory: ServerInventory, policy: CompressPolicy, out_dir: Path) -> list[Path]:
    """Write one compressed schema file per tool plus a TOOLS.md summary.

    Each ``<server>.<tool>.schema.json`` holds the tool's compressed input
    schema as pretty-printed JSON. Returns the written paths (schemas first,
    then TOOLS.md).
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report = build_report(inventory, policy)
    server = inventory.spec.name

    written: list[Path] = []
    for tool in inventory.tools:
        path = out_dir / f"{server}.{tool.name}.schema.json"
        compressed = compress_schema(tool.input_schema, policy)
        path.write_text(json.dumps(compressed, indent=2, ensure_ascii=False) + "\n")
        written.append(path)

    lines = [
        f"# Leaner tool schemas for `{server}`",
        "",
        "Generated by mcp-checkup. Each `.schema.json` sidecar in this directory is a",
        "drop-in, leaner replacement for the corresponding tool's `inputSchema` — same",
        "types, same property names, same `required` list, same `items` structure, just",
        "without the documentation weight that every request pays for. Server authors",
        "can adopt them verbatim.",
        "",
        "| Tool | Before | After | Saved |",
        "| --- | ---: | ---: | ---: |",
    ]
    lines.extend(f"| {r.name} | {r.before} | {r.after} | {r.saved} |" for r in report.rows)
    lines.extend(
        [
            f"| **Total** | {report.total_before} | {report.total_after} | {report.total_saved} |",
            "",
            f"{MEASUREMENT_NOTE}",
            "",
        ]
    )
    tools_md = out_dir / "TOOLS.md"
    tools_md.write_text("\n".join(lines))
    written.append(tools_md)
    return written


def pr_text(inventory: ServerInventory, report: FixReport) -> str:
    """A ready-to-paste GitHub issue body proposing the trimmed schemas upstream."""
    server = inventory.spec.name
    rows = "\n".join(f"| {r.name} | {r.before} | {r.after} | {r.saved} |" for r in report.rows)
    return f"""\
### Trimming tool schemas to reduce the per-request context tax

Hi! Thanks for maintaining this server. I ran mcp-checkup [1] against `{server}` and
measured how many tokens its advertised tool definitions occupy. Because every
connected client resends every tool schema to the model on every request, schema
weight is a recurring "context tax" — it is paid before the user's first message,
on each turn, in every session.

Here is the measured footprint per tool, before and after a semantics-preserving
compression pass (drop `title`/`examples`/`default`/`$comment`/`$schema`/`deprecated`,
trim descriptions to their first sentence, and drop enums over 10 entries in favor
of the base type — no `type`, property names, `required`, or `items` change, and no
currently-valid input becomes invalid):

| Tool | Tokens before | Tokens after | Saved |
| --- | ---: | ---: | ---: |
{rows}
| **Total** | {report.total_before} | {report.total_after} | {report.total_saved} |

That is a {report.pct_saved:.1f}% reduction overall. Measurement method: each tool
definition is serialized to the Anthropic Messages API wire format and tokenized
with tiktoken's o200k_base encoding, so the numbers are estimates (exact for
GPT-4o-family models, a close proxy for others).

Schema weight is also under discussion in the MCP specification repo [2], so
trimming here would benefit users of every client. I have the compressed schemas
generated as sidecar files and would be happy to open a PR applying them if that
is useful.

[1]: {MCP_CHECKUP_URL}
[2]: {MCP_SPEC_ISSUE_URL}
"""


def render_fix_table(report: FixReport, console: Console) -> None:
    """Rich before/after table for *report*, with totals and a % saved footer."""
    table = Table(
        title=f"🧹 {report.server} — compressed schemas ({len(report.rows)} tools)",
        title_justify="left",
    )
    table.add_column("Tool", style="bold")
    table.add_column("Before", justify="right")
    table.add_column("After", justify="right")
    table.add_column("Saved", justify="right")

    for row in sorted(report.rows, key=lambda r: -r.saved):
        table.add_row(row.name, f"{row.before:,}", f"{row.after:,}", f"{row.saved:,}")

    table.add_section()
    table.add_row(
        "[bold]Total[/bold]",
        f"[bold]{report.total_before:,}[/bold]",
        f"[bold]{report.total_after:,}[/bold]",
        f"[bold]{report.total_saved:,}[/bold]",
    )

    console.print(table)
    console.print(f"% saved: {report.pct_saved:.1f}%", highlight=False)
    console.print(f"[dim]{HONESTY_LINE}[/dim]")
