# Copyright (c) mcp-checkup contributors.
# SPDX-License-Identifier: Apache-2.0

"""Model pricing: what the measured token weight costs in USD per model.

Prices come from a vendored snapshot of LiteLLM's price table
(``data/pricing.json``, regenerated by ``scripts/update_pricing.py``).
:func:`load_pricing` can optionally refresh prices live at runtime, falling
back silently to the vendored snapshot when offline.
"""

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from importlib import resources

PRICING_URL = (
    "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
)
_REFRESH_TIMEOUT_SECONDS = 2.0

# One flagship per provider; every entry must exist in the vendored snapshot.
DEFAULT_MODELS: list[str] = ["claude-sonnet-5", "gpt-5.5", "gemini-3.5-flash"]


@dataclass
class ModelPrice:
    """Pricing and context-window facts for one model."""

    key: str
    display: str
    provider: str
    input_cost_per_token: float
    max_input_tokens: int


@dataclass
class CostInfo:
    """What a given token weight costs on one model."""

    usd_per_request: float
    usd_per_session: float
    context_pct: float


def _load_vendored() -> dict[str, ModelPrice]:
    raw = resources.files("mcp_checkup.data").joinpath("pricing.json").read_text("utf-8")
    snapshot = json.loads(raw)
    return {
        key: ModelPrice(
            key=key,
            display=entry["display"],
            provider=entry["provider"],
            input_cost_per_token=entry["input_cost_per_token"],
            max_input_tokens=entry["max_input_tokens"],
        )
        for key, entry in snapshot["models"].items()
    }


def load_pricing(refresh: bool = False) -> dict[str, ModelPrice]:
    """Pricing table keyed by model key, from the vendored snapshot.

    With ``refresh=True``, fetch LiteLLM's live price table and overlay
    up-to-date numbers onto the vendored model set; any failure (offline,
    timeout, malformed response) falls back silently to the snapshot.
    """
    pricing = _load_vendored()
    if not refresh:
        return pricing
    try:
        with urllib.request.urlopen(PRICING_URL, timeout=_REFRESH_TIMEOUT_SECONDS) as resp:
            live = json.load(resp)
        for key, model in pricing.items():
            entry = live.get(key)
            if not isinstance(entry, dict):
                continue
            cost = entry.get("input_cost_per_token")
            max_input = entry.get("max_input_tokens")
            if isinstance(cost, (int, float)):
                model.input_cost_per_token = float(cost)
            if isinstance(max_input, int):
                model.max_input_tokens = max_input
    except Exception:  # offline/refresh failure is expected; the snapshot wins
        pass
    return pricing


def cost_line(model: ModelPrice, tokens: int, turns: int = 1) -> CostInfo:
    """Cost of carrying *tokens* of input on *model*, per request and per session.

    A session re-sends the tool definitions every turn, so session cost is
    simply per-request cost times *turns*.
    """
    usd_per_request = tokens * model.input_cost_per_token
    return CostInfo(
        usd_per_request=usd_per_request,
        usd_per_session=usd_per_request * turns,
        context_pct=tokens / model.max_input_tokens * 100,
    )


def resolve_models(names: list[str] | None, pricing: dict[str, ModelPrice]) -> list[ModelPrice]:
    """Resolve user-supplied model names (or :data:`DEFAULT_MODELS` if None).

    Raises :class:`ValueError` for a name absent from *pricing*, listing the
    available keys.
    """
    resolved = []
    for name in names if names is not None else DEFAULT_MODELS:
        try:
            resolved.append(pricing[name])
        except KeyError:
            available = ", ".join(sorted(pricing))
            raise ValueError(f"unknown model {name!r}; available: {available}") from None
    return resolved
